name = "neversmall"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# @cloudflare/next-on-pages outputs here
pages_build_output_dir = ".vercel/output/static"

[vars]
# Environment variables set via wrangler pages secret
